
{% set data = load_setup_py_data() %}

package:
    name: ts_algorithms
    
    version: {{ data['version'] }}

source:
    path: ../

build:
    number: '0'

requirements:
    build:
        - python
        - setuptools

    run:
        - python
        # dependencies are defined in setup.py
        {% for dep in data['install_requires'] %}
        - {{ dep.lower() }}
        {% endfor %}

about:
    home: https://github.com/ahendriksen/ts_algorithms
    license_file: LICENSE.md
    summary: "A collection of common algorithms for tomosipo"

extra:
    maintainers:
        - Allard Hendriksen
